all:
	cd gcc ; make all
clean:
	cd gcc ; make clean
upload:
	cd gcc ; make upload
startdebug:
	cd gcc ; make startdebug
pin-reset:
	cd gcc ; make pin-reset
erase-all:
	cd gcc ; make erase-all
recover:
	cd gcc ; make recover
