ifeq (PLATFORM, "WINDOWS")
ifeq ($(findstring 86, $(ProgramFiles)), )
	PROGFILES := C:/Program Files
else
	PROGFILES := C:/Program Files (x86)
endif

GNU_INSTALL_ROOT := $(PROGFILES)/GNU Tools ARM Embedded/4.7 2013q3
GNU_VERSION := 4.7.4
GNU_PREFIX := arm-none-eabi

endif

